In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [2]:
df=pd.read_csv('Travel.csv')
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [3]:
print(df['Gender'].value_counts())
print(df['MaritalStatus'].value_counts())

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64
MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [4]:
df['Gender']=df['Gender'].replace('Fe Male','Female')
df['MaritalStatus']=df['MaritalStatus'].replace('Single','Unmarried')

In [5]:
print(df['Gender'].value_counts())
print(df['MaritalStatus'].value_counts())

Gender
Male      2916
Female    1972
Name: count, dtype: int64
MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [6]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [7]:
feature_with_na=[feature for feature in df.columns if df[feature].isnull().sum()>=1]
for feature in feature_with_na:
    print(feature,np.round(df[feature].isnull().mean()*100,5))

Age 4.62357
TypeofContact 0.51146
DurationOfPitch 5.13502
NumberOfFollowups 0.92062
PreferredPropertyStar 0.53191
NumberOfTrips 2.86416
NumberOfChildrenVisiting 1.35025
MonthlyIncome 4.76678

In [8]:
df[feature_with_na].select_dtypes(exclude='object').describe()

,Age,DurationOfPitch,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,NumberOfChildrenVisiting,MonthlyIncome
count,4662.000000,4637.000000,4843.000000,4862.000000,4748.000000,4822.000000,4655.000000
mean,37.622265,15.490835,3.708445,3.581037,3.236521,1.187267,23619.853491
std,9.316387,8.519643,1.002509,0.798009,1.849019,0.857861,5380.698361
min,18.000000,5.000000,1.000000,3.000000,1.000000,0.000000,1000.000000
25%,31.000000,9.000000,3.000000,3.000000,2.000000,1.000000,20346.000000
50%,36.000000,13.000000,4.000000,3.000000,3.000000,1.000000,22347.000000
75%,44.000000,20.000000,4.000000,4.000000,4.000000,2.000000,25571.000000
max,61.000000,127.000000,6.000000,5.000000,22.000000,3.000000,98678.000000

In [9]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['DurationOfPitch']=df['DurationOfPitch'].fillna(df['DurationOfPitch'].mode()[0])
df['NumberOfFollowups']=df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].median())
df['PreferredPropertyStar']=df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0])
df['NumberOfTrips']=df['NumberOfTrips'].fillna(df['NumberOfTrips'].median())
df['NumberOfChildrenVisiting']=df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].median())
df['MonthlyIncome']=df['MonthlyIncome'].fillna(df['MonthlyIncome'].mode()[0])
df['TypeofContact']=df['TypeofContact'].fillna(df['TypeofContact'].mode()[0])
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [10]:
df.drop('CustomerID',inplace=True,axis=1)

In [11]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [12]:
df['TotalVisiting']=df['NumberOfPersonVisiting']+df['NumberOfChildrenVisiting']
df.drop(['NumberOfPersonVisiting','NumberOfChildrenVisiting'],inplace=True,axis=1)

In [13]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [14]:
num_features=[feature for feature in df.columns if df[feature].dtype!='str' ]
print('Number of Numeric features :',len(num_features))
cat_features=[feature for feature in df.columns if df[feature].dtype=='str']
print('Number of Catagorial features :',len(cat_features))
dis_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Number of Discrete features :',len(dis_features))
conti_feature=[feature for feature in num_features if feature not in dis_features]
print('Number of Continious features :',len(conti_feature))

Number of Numeric features : 12
Number of Catagorial features : 6
Number of Discrete features : 9
Number of Continious features : 3

In [15]:
X=df.drop('ProdTaken',axis=1)
y=df['ProdTaken']

In [16]:
num_feature=[feature for feature in X.columns if X[feature].dtype!='str']
cat_feature=[feature for feature in X.columns if X[feature].dtype=='str']

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)
X_test.shape,X_train.shape

((1222, 17), (3666, 17))

In [18]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
num_trans=StandardScaler()
cat_trans=OneHotEncoder(drop='first')
preprocessing=ColumnTransformer(
    [
        ('OneHotEncoder',cat_trans,cat_feature),
        ('StandardScaler',num_trans,num_feature)
    ]
)
X_train=preprocessing.fit_transform(X_train)
X_test=preprocessing.transform(X_test)
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.457451,0.557184,0.293827,1.779100,-0.121627,-0.648791,-1.518110,0.782845,-0.618792,-0.787284
1,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.718930,-1.104944,-0.711935,1.779100,0.995879,-0.648791,0.678755,0.782845,-1.109718,0.626126
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-0.718930,0.082290,1.299590,-0.730879,-1.239133,-0.648791,1.411044,-1.277392,-0.909822,-1.493989
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.718930,-0.630050,0.293827,-0.730879,-0.121627,-0.648791,-0.053533,0.782845,-0.468588,1.332831
4,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.718930,-0.036433,-0.711935,-0.730879,0.437126,-0.648791,-0.053533,0.782845,-1.159786,-0.787284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3661,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.718930,-0.273880,-0.711935,0.524110,-0.121627,-0.648791,-1.518110,-1.277392,-1.171412,0.626126
3662,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.718930,1.032077,0.293827,-0.730879,-0.121627,1.541328,1.411044,0.782845,-0.410270,-0.080579
3663,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,...,-0.718930,-0.748773,-0.711935,1.779100,1.554631,1.541328,-0.053533,-1.277392,-1.109718,-0.787284
3664,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.718930,0.082290,1.299590,1.779100,-0.680380,1.541328,-0.053533,-1.277392,-0.423959,0.626126
3665,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.369261,-0.867497,-0.711935,0.524110,1.554631,-0.648791,-0.053533,0.782845,-1.062838,0.626126

In [21]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix,f1_score,accuracy_score,roc_auc_score

In [22]:
models={
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Adaboost Model':AdaBoostClassifier()
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)
    print(list(models.keys())[i])
    print("Classification report",classification_report(y_test,y_pred))
    print("confustion matrix :",confusion_matrix(y_test,y_pred))
    print("accuracy_score :",accuracy_score(y_test,y_pred))
    print('f1_score :',f1_score(y_test,y_pred))
    print('Roc Auc Score :',roc_auc_score(y_test,y_pred))
    print("\n")

Decision Tree
Classification report               precision    recall  f1-score   support

           0       0.95      0.95      0.95      1019
           1       0.75      0.75      0.75       203

    accuracy                           0.92      1222
   macro avg       0.85      0.85      0.85      1222
weighted avg       0.92      0.92      0.92      1222

confustion matrix : [[969  50]
 [ 50 153]]
accuracy_score : 0.9181669394435352
f1_score : 0.7536945812807881
Roc Auc Score : 0.8523134339181173


Random Forest
Classification report               precision    recall  f1-score   support

           0       0.93      0.99      0.96      1019
           1       0.94      0.62      0.75       203

    accuracy                           0.93      1222
   macro avg       0.93      0.81      0.85      1222
weighted avg       0.93      0.93      0.92      1222

confustion matrix : [[1011    8]
 [  77  126]]
accuracy_score : 0.9304418985270049
f1_score : 0.7477744807121661
Roc Auc Score : 0.8064194105106426


Adaboost Model
Classification report               precision    recall  f1-score   support

           0       0.87      0.97      0.92      1019
           1       0.65      0.25      0.36       203

    accuracy                           0.85      1222
   macro avg       0.76      0.61      0.64      1222
weighted avg       0.83      0.85      0.82      1222

confustion matrix : [[991  28]
 [152  51]]
accuracy_score : 0.8527004909983633
f1_score : 0.3617021276595745
Roc Auc Score : 0.6118768037823231

In [23]:
gv_parms={
    'n_estimators':[100,200,300,400,500,1000],
    'learning_rate':[1,2,3,4,5,10]
}
gv_model=[
    ('rf',AdaBoostClassifier(),gv_parms)
]
gv_model

[('rf',
  AdaBoostClassifier(),
  {'n_estimators': [100, 200, 300, 400, 500, 1000],
   'learning_rate': [1, 2, 3, 4, 5, 10]})]

In [24]:
from sklearn.model_selection import GridSearchCV
ht_parms={}
for name,model,params in gv_model:
    grid=GridSearchCV(model,param_grid=params,cv=5,verbose=3,refit=True)
    grid.fit(X_train,y_train)
    g_pred=grid.predict(X_test)
    print("Classification report",classification_report(y_test,g_pred))
    print("confustion matrix :",confusion_matrix(y_test,g_pred))
    print("accuracy_score :",accuracy_score(y_test,g_pred))
    print('f1_score :',f1_score(y_test,g_pred))
    print('Roc Auc Score :',roc_auc_score(y_test,g_pred))
    print("\n")

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV 1/5] END .learning_rate=1, n_estimators=100;, score=0.849 total time=   0.2s
[CV 2/5] END .learning_rate=1, n_estimators=100;, score=0.839 total time=   0.2s
[CV 3/5] END .learning_rate=1, n_estimators=100;, score=0.846 total time=   0.2s
[CV 4/5] END .learning_rate=1, n_estimators=100;, score=0.839 total time=   0.1s
[CV 5/5] END .learning_rate=1, n_estimators=100;, score=0.832 total time=   0.1s
[CV 1/5] END .learning_rate=1, n_estimators=200;, score=0.851 total time=   0.4s
[CV 2/5] END .learning_rate=1, n_estimators=200;, score=0.836 total time=   0.5s
[CV 3/5] END .learning_rate=1, n_estimators=200;, score=0.844 total time=   0.4s
[CV 4/5] END .learning_rate=1, n_estimators=200;, score=0.840 total time=   0.4s
[CV 5/5] END .learning_rate=1, n_estimators=200;, score=0.842 total time=   0.4s
[CV 1/5] END .learning_rate=1, n_estimators=300;, score=0.851 total time=   0.7s
[CV 2/5] END .learning_rate=1, n_estimators=300;, score=0.838 total time=   0.7s
[CV 3/5] END .learning_rate=1, n_estimators=300;, score=0.843 total time=   0.7s
[CV 4/5] END .learning_rate=1, n_estimators=300;, score=0.849 total time=   0.8s
[CV 5/5] END .learning_rate=1, n_estimators=300;, score=0.842 total time=   0.7s
[CV 1/5] END .learning_rate=1, n_estimators=400;, score=0.856 total time=   1.0s
[CV 2/5] END .learning_rate=1, n_estimators=400;, score=0.838 total time=   0.9s
[CV 3/5] END .learning_rate=1, n_estimators=400;, score=0.840 total time=   0.9s
[CV 4/5] END .learning_rate=1, n_estimators=400;, score=0.847 total time=   0.9s
[CV 5/5] END .learning_rate=1, n_estimators=400;, score=0.840 total time=   0.9s
[CV 1/5] END .learning_rate=1, n_estimators=500;, score=0.851 total time=   1.2s
[CV 2/5] END .learning_rate=1, n_estimators=500;, score=0.838 total time=   1.1s
[CV 3/5] END .learning_rate=1, n_estimators=500;, score=0.840 total time=   1.1s
[CV 4/5] END .learning_rate=1, n_estimators=500;, score=0.850 total time=   1.1s
[CV 5/5] END .learning_rate=1, n_estimators=500;, score=0.840 total time=   1.1s
[CV 1/5] END learning_rate=1, n_estimators=1000;, score=0.846 total time=   2.3s
[CV 2/5] END learning_rate=1, n_estimators=1000;, score=0.842 total time=   2.2s
[CV 3/5] END learning_rate=1, n_estimators=1000;, score=0.835 total time=   2.2s
[CV 4/5] END learning_rate=1, n_estimators=1000;, score=0.850 total time=   2.3s
[CV 5/5] END learning_rate=1, n_estimators=1000;, score=0.838 total time=   2.2s
[CV 1/5] END .learning_rate=2, n_estimators=100;, score=0.804 total time=   0.1s
[CV 2/5] END .learning_rate=2, n_estimators=100;, score=0.195 total time=   0.1s
[CV 3/5] END .learning_rate=2, n_estimators=100;, score=0.195 total time=   0.1s
[CV 4/5] END .learning_rate=2, n_estimators=100;, score=0.195 total time=   0.1s
[CV 5/5] END .learning_rate=2, n_estimators=100;, score=0.804 total time=   0.1s
[CV 1/5] END .learning_rate=2, n_estimators=200;, score=0.804 total time=   0.4s
[CV 2/5] END .learning_rate=2, n_estimators=200;, score=0.195 total time=   0.4s
[CV 3/5] END .learning_rate=2, n_estimators=200;, score=0.195 total time=   0.4s
[CV 4/5] END .learning_rate=2, n_estimators=200;, score=0.195 total time=   0.4s
[CV 5/5] END .learning_rate=2, n_estimators=200;, score=0.804 total time=   0.4s
[CV 1/5] END .learning_rate=2, n_estimators=300;, score=0.804 total time=   0.6s
[CV 2/5] END .learning_rate=2, n_estimators=300;, score=0.195 total time=   0.6s
[CV 3/5] END .learning_rate=2, n_estimators=300;, score=0.195 total time=   0.6s
[CV 4/5] END .learning_rate=2, n_estimators=300;, score=0.195 total time=   0.6s
[CV 5/5] END .learning_rate=2, n_estimators=300;, score=0.804 total time=   0.6s
[CV 1/5] END .learning_rate=2, n_estimators=400;, score=0.804 total time=   0.9s
[CV 2/5] END .learning_rate=2, n_estimators=400;, score=0.195 total time=   0.9s
[CV 3/5] END .learning_rate=2, n_estimators=400;, score=0.195 total time=   0.8s
[CV 4/5] END .learning_rate=2, n_estimators=400;, score=0.195 total time=   0.8s
[CV 5/5] END .learning_rate=2, n_estimators=400;, score=0.804 total time=   0.9s
[CV 1/5] END .learning_rate=2, n_estimators=500;, score=0.804 total time=   1.1s
[CV 2/5] END .learning_rate=2, n_estimators=500;, score=0.195 total time=   1.1s
[CV 3/5] END .learning_rate=2, n_estimators=500;, score=0.195 total time=   1.2s
[CV 4/5] END .learning_rate=2, n_estimators=500;, score=0.195 total time=   1.1s
[CV 5/5] END .learning_rate=2, n_estimators=500;, score=0.804 total time=   1.1s
[CV 1/5] END learning_rate=2, n_estimators=1000;, score=0.804 total time=   2.3s
[CV 2/5] END learning_rate=2, n_estimators=1000;, score=0.195 total time=   2.3s
[CV 3/5] END learning_rate=2, n_estimators=1000;, score=0.195 total time=   2.3s
[CV 4/5] END learning_rate=2, n_estimators=1000;, score=0.195 total time=   2.3s
[CV 5/5] END learning_rate=2, n_estimators=1000;, score=0.804 total time=   2.3s
[CV 1/5] END .learning_rate=3, n_estimators=100;, score=0.804 total time=   0.1s
[CV 2/5] END .learning_rate=3, n_estimators=100;, score=0.805 total time=   0.1s
[CV 3/5] END .learning_rate=3, n_estimators=100;, score=0.804 total time=   0.1s
[CV 4/5] END .learning_rate=3, n_estimators=100;, score=0.804 total time=   0.2s
[CV 5/5] END .learning_rate=3, n_estimators=100;, score=0.804 total time=   0.1s
[CV 1/5] END .learning_rate=3, n_estimators=200;, score=0.804 total time=   0.4s
[CV 2/5] END .learning_rate=3, n_estimators=200;, score=0.805 total time=   0.4s
[CV 3/5] END .learning_rate=3, n_estimators=200;, score=0.804 total time=   0.4s
[CV 4/5] END .learning_rate=3, n_estimators=200;, score=0.804 total time=   0.4s
[CV 5/5] END .learning_rate=3, n_estimators=200;, score=0.804 total time=   0.4s
[CV 1/5] END .learning_rate=3, n_estimators=300;, score=0.804 total time=   0.6s
[CV 2/5] END .learning_rate=3, n_estimators=300;, score=0.805 total time=   0.6s
[CV 3/5] END .learning_rate=3, n_estimators=300;, score=0.804 total time=   0.6s
[CV 4/5] END .learning_rate=3, n_estimators=300;, score=0.804 total time=   0.6s
[CV 5/5] END .learning_rate=3, n_estimators=300;, score=0.804 total time=   0.6s
[CV 1/5] END .learning_rate=3, n_estimators=400;, score=0.804 total time=   0.9s
[CV 2/5] END .learning_rate=3, n_estimators=400;, score=0.805 total time=   0.9s
[CV 3/5] END .learning_rate=3, n_estimators=400;, score=0.804 total time=   0.8s
[CV 4/5] END .learning_rate=3, n_estimators=400;, score=0.804 total time=   0.8s
[CV 5/5] END .learning_rate=3, n_estimators=400;, score=0.804 total time=   0.8s
[CV 1/5] END .learning_rate=3, n_estimators=500;, score=0.804 total time=   1.1s
[CV 2/5] END .learning_rate=3, n_estimators=500;, score=0.805 total time=   1.1s
[CV 3/5] END .learning_rate=3, n_estimators=500;, score=0.804 total time=   1.1s
[CV 4/5] END .learning_rate=3, n_estimators=500;, score=0.804 total time=   1.1s
[CV 5/5] END .learning_rate=3, n_estimators=500;, score=0.804 total time=   1.1s
[CV 1/5] END learning_rate=3, n_estimators=1000;, score=0.804 total time=   2.3s
[CV 2/5] END learning_rate=3, n_estimators=1000;, score=0.805 total time=   2.3s
[CV 3/5] END learning_rate=3, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 4/5] END learning_rate=3, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 5/5] END learning_rate=3, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 1/5] END .learning_rate=4, n_estimators=100;, score=0.804 total time=   0.1s
[CV 2/5] END .learning_rate=4, n_estimators=100;, score=0.805 total time=   0.1s
[CV 3/5] END .learning_rate=4, n_estimators=100;, score=0.804 total time=   0.2s
[CV 4/5] END .learning_rate=4, n_estimators=100;, score=0.804 total time=   0.1s
[CV 5/5] END .learning_rate=4, n_estimators=100;, score=0.804 total time=   0.1s
[CV 1/5] END .learning_rate=4, n_estimators=200;, score=0.804 total time=   0.4s
[CV 2/5] END .learning_rate=4, n_estimators=200;, score=0.805 total time=   0.4s
[CV 3/5] END .learning_rate=4, n_estimators=200;, score=0.804 total time=   0.4s
[CV 4/5] END .learning_rate=4, n_estimators=200;, score=0.804 total time=   0.4s
[CV 5/5] END .learning_rate=4, n_estimators=200;, score=0.804 total time=   0.4s
[CV 1/5] END .learning_rate=4, n_estimators=300;, score=0.804 total time=   0.6s
[CV 2/5] END .learning_rate=4, n_estimators=300;, score=0.805 total time=   0.6s
[CV 3/5] END .learning_rate=4, n_estimators=300;, score=0.804 total time=   0.6s
[CV 4/5] END .learning_rate=4, n_estimators=300;, score=0.804 total time=   0.7s
[CV 5/5] END .learning_rate=4, n_estimators=300;, score=0.804 total time=   0.6s
[CV 1/5] END .learning_rate=4, n_estimators=400;, score=0.804 total time=   0.9s
[CV 2/5] END .learning_rate=4, n_estimators=400;, score=0.805 total time=   0.8s
[CV 3/5] END .learning_rate=4, n_estimators=400;, score=0.804 total time=   0.8s
[CV 4/5] END .learning_rate=4, n_estimators=400;, score=0.804 total time=   0.9s
[CV 5/5] END .learning_rate=4, n_estimators=400;, score=0.804 total time=   0.8s
[CV 1/5] END .learning_rate=4, n_estimators=500;, score=0.804 total time=   1.1s
[CV 2/5] END .learning_rate=4, n_estimators=500;, score=0.805 total time=   1.1s
[CV 3/5] END .learning_rate=4, n_estimators=500;, score=0.804 total time=   1.1s
[CV 4/5] END .learning_rate=4, n_estimators=500;, score=0.804 total time=   1.1s
[CV 5/5] END .learning_rate=4, n_estimators=500;, score=0.804 total time=   1.2s
[CV 1/5] END learning_rate=4, n_estimators=1000;, score=0.804 total time=   2.4s
[CV 2/5] END learning_rate=4, n_estimators=1000;, score=0.805 total time=   2.2s
[CV 3/5] END learning_rate=4, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 4/5] END learning_rate=4, n_estimators=1000;, score=0.804 total time=   2.1s
[CV 5/5] END learning_rate=4, n_estimators=1000;, score=0.804 total time=   2.1s
[CV 1/5] END .learning_rate=5, n_estimators=100;, score=0.804 total time=   0.1s
[CV 2/5] END .learning_rate=5, n_estimators=100;, score=0.805 total time=   0.1s
[CV 3/5] END .learning_rate=5, n_estimators=100;, score=0.804 total time=   0.1s
[CV 4/5] END .learning_rate=5, n_estimators=100;, score=0.804 total time=   0.1s
[CV 5/5] END .learning_rate=5, n_estimators=100;, score=0.804 total time=   0.1s
[CV 1/5] END .learning_rate=5, n_estimators=200;, score=0.804 total time=   0.4s
[CV 2/5] END .learning_rate=5, n_estimators=200;, score=0.805 total time=   0.4s
[CV 3/5] END .learning_rate=5, n_estimators=200;, score=0.804 total time=   0.4s
[CV 4/5] END .learning_rate=5, n_estimators=200;, score=0.804 total time=   0.4s
[CV 5/5] END .learning_rate=5, n_estimators=200;, score=0.804 total time=   0.4s
[CV 1/5] END .learning_rate=5, n_estimators=300;, score=0.804 total time=   0.6s
[CV 2/5] END .learning_rate=5, n_estimators=300;, score=0.805 total time=   0.6s
[CV 3/5] END .learning_rate=5, n_estimators=300;, score=0.804 total time=   0.6s
[CV 4/5] END .learning_rate=5, n_estimators=300;, score=0.804 total time=   0.6s
[CV 5/5] END .learning_rate=5, n_estimators=300;, score=0.804 total time=   0.6s
[CV 1/5] END .learning_rate=5, n_estimators=400;, score=0.804 total time=   0.8s
[CV 2/5] END .learning_rate=5, n_estimators=400;, score=0.805 total time=   0.8s
[CV 3/5] END .learning_rate=5, n_estimators=400;, score=0.804 total time=   0.8s
[CV 4/5] END .learning_rate=5, n_estimators=400;, score=0.804 total time=   0.8s
[CV 5/5] END .learning_rate=5, n_estimators=400;, score=0.804 total time=   0.8s
[CV 1/5] END .learning_rate=5, n_estimators=500;, score=0.804 total time=   1.0s
[CV 2/5] END .learning_rate=5, n_estimators=500;, score=0.805 total time=   1.0s
[CV 3/5] END .learning_rate=5, n_estimators=500;, score=0.804 total time=   1.0s
[CV 4/5] END .learning_rate=5, n_estimators=500;, score=0.804 total time=   1.1s
[CV 5/5] END .learning_rate=5, n_estimators=500;, score=0.804 total time=   1.0s
[CV 1/5] END learning_rate=5, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 2/5] END learning_rate=5, n_estimators=1000;, score=0.805 total time=   2.2s
[CV 3/5] END learning_rate=5, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 4/5] END learning_rate=5, n_estimators=1000;, score=0.804 total time=   2.1s
[CV 5/5] END learning_rate=5, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 1/5] END learning_rate=10, n_estimators=100;, score=0.804 total time=   0.1s
[CV 2/5] END learning_rate=10, n_estimators=100;, score=0.805 total time=   0.1s
[CV 3/5] END learning_rate=10, n_estimators=100;, score=0.804 total time=   0.1s
[CV 4/5] END learning_rate=10, n_estimators=100;, score=0.804 total time=   0.1s
[CV 5/5] END learning_rate=10, n_estimators=100;, score=0.804 total time=   0.1s
[CV 1/5] END learning_rate=10, n_estimators=200;, score=0.804 total time=   0.4s
[CV 2/5] END learning_rate=10, n_estimators=200;, score=0.805 total time=   0.4s
[CV 3/5] END learning_rate=10, n_estimators=200;, score=0.804 total time=   0.4s
[CV 4/5] END learning_rate=10, n_estimators=200;, score=0.804 total time=   0.4s
[CV 5/5] END learning_rate=10, n_estimators=200;, score=0.804 total time=   0.4s
[CV 1/5] END learning_rate=10, n_estimators=300;, score=0.804 total time=   0.6s
[CV 2/5] END learning_rate=10, n_estimators=300;, score=0.805 total time=   0.6s
[CV 3/5] END learning_rate=10, n_estimators=300;, score=0.804 total time=   0.6s
[CV 4/5] END learning_rate=10, n_estimators=300;, score=0.804 total time=   0.6s
[CV 5/5] END learning_rate=10, n_estimators=300;, score=0.804 total time=   0.6s
[CV 1/5] END learning_rate=10, n_estimators=400;, score=0.804 total time=   0.8s
[CV 2/5] END learning_rate=10, n_estimators=400;, score=0.805 total time=   0.8s
[CV 3/5] END learning_rate=10, n_estimators=400;, score=0.804 total time=   0.8s
[CV 4/5] END learning_rate=10, n_estimators=400;, score=0.804 total time=   0.8s
[CV 5/5] END learning_rate=10, n_estimators=400;, score=0.804 total time=   0.8s
[CV 1/5] END learning_rate=10, n_estimators=500;, score=0.804 total time=   1.1s
[CV 2/5] END learning_rate=10, n_estimators=500;, score=0.805 total time=   1.0s
[CV 3/5] END learning_rate=10, n_estimators=500;, score=0.804 total time=   1.0s
[CV 4/5] END learning_rate=10, n_estimators=500;, score=0.804 total time=   1.0s
[CV 5/5] END learning_rate=10, n_estimators=500;, score=0.804 total time=   1.1s
[CV 1/5] END learning_rate=10, n_estimators=1000;, score=0.804 total time=   2.2s
[CV 2/5] END learning_rate=10, n_estimators=1000;, score=0.805 total time=   2.2s
[CV 3/5] END learning_rate=10, n_estimators=1000;, score=0.804 total time=   2.1s
[CV 4/5] END learning_rate=10, n_estimators=1000;, score=0.804 total time=   2.1s
[CV 5/5] END learning_rate=10, n_estimators=1000;, score=0.804 total time=   2.2s
Classification report               precision    recall  f1-score   support

           0       0.87      0.97      0.92      1019
           1       0.69      0.30      0.42       203

    accuracy                           0.86      1222
   macro avg       0.78      0.64      0.67      1222
weighted avg       0.84      0.86      0.84      1222

confustion matrix : [[991  28]
 [142  61]]
accuracy_score : 0.8608837970540099
f1_score : 0.4178082191780822
Roc Auc Score : 0.6365073456542442